version: '2'
services:
  mydbcontainer:
    image: mariadb:10.3
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./mariadb:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=expertize_development"
      - "MYSQL_USER=expertize"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "3306:3306"
